# Generated by Django 3.2.7 on 2021-09-30 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localidades', '0003_rename_localidade_localidade_nome'),
        ('secretarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretario',
            name='localidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='localidades.localidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
