# Generated by Django 3.2.7 on 2021-10-06 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0004_remove_turma_pert_secret'),
        ('secretarios', '0002_auto_20210930_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretario',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='secretario',
            name='user',
        ),
        migrations.AddField(
            model_name='secretario',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='turmas.turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
