# Generated by Django 3.2.7 on 2021-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('ID_Localidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome da Igreja', max_length=40)),
            ],
        ),
    ]
