# Generated by Django 3.2.7 on 2021-09-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidade',
            name='nome',
        ),
        migrations.AddField(
            model_name='localidade',
            name='localidade',
            field=models.CharField(choices=[('Maranatha - Cong. Carolina', 'Maranatha - Cong. Carolina'), ('XXX - Sede do Setor', 'XXX - Sede do Setor')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
