# Generated by Django 3.2.7 on 2021-09-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0002_auto_20210930_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidade',
            old_name='localidade',
            new_name='nome',
        ),
    ]
