# Generated by Django 3.2.7 on 2021-09-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0003_rename_localidade_localidade_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidade',
            old_name='nome',
            new_name='nomeLocalidade',
        ),
    ]
