# Generated by Django 3.2.7 on 2021-10-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0004_rename_nome_localidade_nomelocalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='nomeLocalidade',
            field=models.CharField(choices=[('Maranatha - Cong. Carolina', 'Maranatha - Cong. Carolina'), ('XXX - Sede do Setor', 'XXX - Sede do Setor')], max_length=100, verbose_name='Igreja'),
        ),
    ]
