# Generated by Django 3.2.7 on 2021-10-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0006_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
