# Generated by Django 3.2.7 on 2021-09-30 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('ID_Turma', models.AutoField(primary_key=True, serialize=False)),
                ('turma', models.CharField(max_length=45)),
                ('modalidade', models.CharField(choices=[('Adolescentes', 'Adolescentes'), ('Adulto', 'Adulto'), ('Infantil', 'Infantil'), ('Jovens', 'Jovens'), ('Juvenis', 'Juvenis'), ('Pré-Adolescentes', 'Pré-Adolescentes')], max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 9, 30, 15, 46, 3, 15231))),
            ],
        ),
    ]
