# Generated by Django 3.2.7 on 2021-09-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='date',
        ),
    ]
