# Generated by Django 3.2.7 on 2021-09-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretarios', '0002_auto_20210930_1732'),
        ('turmas', '0002_remove_turma_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='pert_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretarios.secretario'),
        ),
    ]
