# Generated by Django 3.2.7 on 2021-10-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_turma_pert_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='pert_secret',
        ),
    ]
