# Generated by Django 3.2.7 on 2021-09-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpf',
            fields=[
                ('ID_Cpf', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('ID_Pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.cpf')),
            ],
        ),
    ]
