# Generated by Django 3.2.7 on 2021-09-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.cpf'),
        ),
    ]
