# Generated by Django 3.2.7 on 2021-10-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_pessoa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data',
            field=models.DateField(max_length=10),
        ),
    ]
