# Generated by Django 3.2.7 on 2021-10-05 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_remove_pessoa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, max_length=8, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
