# Generated by Django 3.2.7 on 2021-10-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
