# Generated by Django 3.2.7 on 2021-10-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0004_professor_localidade_ptr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
    ]
