# Generated by Django 3.2.7 on 2021-09-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0004_rename_nome_localidade_nomelocalidade'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='localidade_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='localidades.localidade'),
            preserve_default=False,
        ),
    ]
