# Generated by Django 3.2.7 on 2021-10-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_auto_20211001_1225'),
        ('alunos', '0002_aluno_localidade_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoas.cpf'),
            preserve_default=False,
        ),
    ]
