# Generated by Django 3.2.7 on 2021-10-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_telefone'),
        ('alunos', '0003_aluno_cpf_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='pessoas.telefone'),
            preserve_default=False,
        ),
    ]
