# Generated by Django 3.2.7 on 2021-10-03 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_telefone_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 10, 3, 15, 50, 46, 163687, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
