# Generated by Django 3.2.7 on 2021-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_alter_aluno_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
