# Generated by Django 3.2.7 on 2021-10-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_aluno_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='age',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data',
        ),
    ]
